---
- hosts: all
  become: yes
  become_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3
    odoo_dependencies:
      - python3
      - python3-pip
      - python-virtualenv
      - wget
      - git
      - unzip
      - libpq-dev
      - libldap2-dev
      - libsasl2-dev
      - libxml2-dev
      - libevent-dev
      - libxslt1-dev

  tasks:
    - name: Ensure group exists for system user
      group:
        name: "odoo"
        state: present
    - name: Create System User
      user:
        name: "odoo"
        shell: /bin/bash
        group: "odoo"
        state: present
    - name: Install System Dependencies
      apt:
        name: "{{ odoo_dependencies }}"
